# Generated by Django 5.0.6 on 2024-07-09 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='eg. pizza, pasta', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('people', models.PositiveSmallIntegerField()),
                ('date', models.DateTimeField()),
                ('message', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('recipe', models.CharField(max_length=100)),
                ('tag', models.CharField(blank=True, choices=[('hot!', 'hot!'), ('popular', 'popular'), ('special', 'special'), ('seasonal', 'seasonal')], max_length=15, null=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.menu')),
            ],
            options={
                'verbose_name_plural': 'Dishes',
            },
        ),
    ]
